export const GET_ALL_ORDERS = 'GET_ALL_ORDERS'
export const START_ALL_ORDERS = 'START_ALL_ORDERS'
export const GET_ALL_ORDERS_SUCCESS = 'ALL_ORDERS_SUCCESS'
export const ALL_ORDERS_FAILTURE = 'ALL_ORDERS_FAILTURE'
export const STOP_ALL_ORDERS = 'STOP_ALL_ORDERS'

export const START_FILTER = 'START_FILTER'

export const FILTER_SUCCESS = 'FILTER_SUCCESS'

export const FILTER_FAILTURE = 'FILTER_FAILTURE'
export const STOP_FILTER = 'STOP_FILTER'